Create unit tests for Product - Interest  Rate module
BancoBanQuito/product-banquito pull request #2
Opened 2023-02-12 23:08 UTC by jlgalarza3

2023-02-12 23:38 UTC, listerineh requested changes

2023-02-12 23:38 UTC, listerineh commented on product/src/test/java/com/banquito/product/mock/InterestRateMock.java
> +}
porfa usa los mocks, no hagas .builder en los tests, se vuelve algo repetitivo

2023-02-13 23:15 UTC, jlgalarza3 commented on product/src/test/java/com/banquito/product/mock/InterestRateMock.java
> +}
🆗

2023-02-15 22:29 UTC, listerineh approved these changes

2023-02-15 22:29 UTC, merged